### PR TITLE
Add a php new ini setting of yaml.decode_bool

### PR DESCRIPTION
**Pull request by takahashi-yugo**
Hi,

I added new php ini setting to change a treatment for english boolean words like 'Yes' and 'No'.
The treatment can be changed as followings.
* When yaml.decode_bool=0, the parser recongnizes no english boolean words as bool('Yes' will be treated as string). 
* When yaml.decode_bool=1, the parser recongnizes english boolean words as bool. this is the default treatment.
* When yaml.decode_bool=2, the parser recongnizes english boolean words except abbreviation style(Y, y, N, and n) as bool.

The default treatment is same as now. 
I just wanted this feature 😄  
But if someone already work on this, I close this PR.

thanks!

### CODE REVIEW

**Comment by johannes** [comment]
I have no role in this module, but I'd strongly suggest to move such options in the `yaml_parse()` function. (Or creating a new interface) Putting such decisions in the ini means that a wrong configuration can break applications.  PHP historically made the mistake to provide too many options, leading to many issues ...

**Comment by takahashi-yugo** [comment]
@johannes
thanks for good feedback.

The reason I added the new ini setting is that the parser's behavior is changed now through ini settings like `yaml.decode_binary` and `yaml.decode_php` and `yaml.decode_timestamp`.
I thought it would be better by according to that way because  `yaml.decode_bool`  also change  parser's behavior.

But I agree your opinion and understand that specifing by `yaml_parse()` function's option is more explicit and impact will be limited.

I would like to listen  more people's opinions for discussing which interface is better.

thanks

**Comment by bd808** [comment]
* `yaml.decode_php` is a security band-aid.
* `yaml.decode_binary` and `yaml.decode_timestamp` are relics of the original tarball that the rebooted project started from (4248d229d1e306aa3df9b6bb9a3efd958a6bf451)

Generally, the way to keep values that the YAML spec considers special is to quote them. There are many 'interesting' default conversions in [the spec](http://yaml.org/type/) ([sexagesimal integers](http://yaml.org/type/int.html) come to mind) that could trip up a document author in addition to the wide range of values considered to be booleans.

One of the purposes of YAML is to provide a language independent serialization format for complex data. When this YAML parser or any other adds parse time flags that alter the behavior from the spec this language independence is broken. This can lead to very confusing bugs when files are shared with other consumers or the original application decides for whatever reason to replace the parser with another implementation. My job as the library maintainer is not to prevent consumer applications from getting their work done, but I'd rather not help them load the guns that they are pointing at their own feet.

**Comment by takahashi-yugo** [comment]
@bd808
Thanks for your reply.

As you say, this change is confusing for PHP users and may lead to bugs. 
In Addition, PHP users have the way to keep values. Thanks for your opinion.
I totally agree with you and close this PR.

**Pull request closed without merging**
