### PR TITLE
Fix build on PHP 7.3

### PR DESCRIPTION
**Pull request by dktapps**
fixes https://github.com/php/pecl-file_formats-yaml/pull/30#issuecomment-381415730

### CODE REVIEW

**Comment by petk** [comment]
Thanks for this... :+1:  Bug report has been submitted here:
https://bugs.php.net/bug.php?id=76522

**Comment by remicollet** [comment]
Please also add 7.1, 72 and nightly to .travis.xml file

BTW, on a local build, still 1 test failure

```
TEST 23/67 [tests/yaml_emit_007.phpt]
========DIFF========
001+ string(29) "---
001- string(56) "---
004+ c: *refid1
004- c: &refid1
005-   a: a
006-   b: b
007-   c: *refid1
========DONE========
FAIL yaml_emit - recursive structures [tests/yaml_emit_007.phpt] 

```

**Comment by dktapps** [comment]
@remicollet I ran tests on Windows and there was a lot of noise there (due to newline issues \n vs \r\n, might need fixing separately), so I didn't notice that test failure 🙄 I'll take a look at it later when I can get on a linux machine.

**Comment by petk** [comment]
Note that there is a PR for these changes here #30

**Comment by remicollet** [comment]
See PR #33 with an happy travis result \o/

**Comment by remicollet** [comment]
Fixed by PR #33 which is merged

**Pull request closed without merging**
