### PR TITLE
PHP7 Support

### PR DESCRIPTION
**Pull request by Sean-Der**
Hey @bd808 !

This is the start of PHP 7 support, this still currently has [test fails](https://gist.github.com/Sean-Der/930eadc50af1662a2c70) though.

Currently 5.5 is only at 75% pass rate [test fails](https://gist.github.com/Sean-Der/dda8a7f03f8e24e66451) would you be interested after I am finished with 7 in me fixing those?

So feel free to ignore the diff till I come back with 100%! I just wanted to make sure I have this PR open before someone else starts work on this.

thanks!

### CODE REVIEW

**Comment by Sean-Der** [comment]
Also, what would you like me to do about IS_UNICODE?

6 is officially dead so would you like me to pull that out? Or leave that be to keep the diff cleaner.

**Comment by bd808** [comment]
> Also, what would you like me to do about IS_UNICODE?

If you have the energy feel free to rip it out. We can do it in another patch set too. Either is fine with me. There is some other old cruft for supporting <5.3 that can probably be ripped out too. Keeping 5.3+ support would be nice if we can since LTS distributions shipping with 5.3.x have quite a while left to live (eg Ubuntu 12.04).

**Comment by bd808** [comment]
> Currently 5.5 is only at 75% pass rate test fails would you be interested after I am finished with 7 in me fixing those?

The test failures you are seeing for 5.5 are new to me. The tests all pass for me locally and in the last run on TravisCI (https://travis-ci.org/php/pecl-file_formats-yaml/builds/63031752). It looks like you are getting failures from a ZTS build though and I'm not sure I have tested using ZTS in a while. I'll see if I can find some time to fire up a set of ZTS tests and reproduce.

**Comment by Sean-Der** [comment]
Good news @bd808 ! We are now at 100% pass rate with PHP 7 on non-zts :D 

You mind giving this a look over? I need to close out some other bugs that people have filed against my stuff, and then I will be back to fix my memory leaks.

thanks!

**Comment by Sean-Der** [comment]
@bd808 thoughts on this? What/where would you like me to go from here? Fix leaks in 5 and/or 7 etc...

Also, I noticed that yaml exists in a couple different places for version control + bug tracking, would it be helpful if I could spend some time merging them into one place?

thanks!

**Comment by bd808** [comment]
I'm getting 5 test failures and a lot of compiler warnings against a local build of PHP 7.0.0alpha2

* Test PECL bug #69465 [tests/bug_69465.phpt]
  * Segmentation fault (core dumped)
* yaml - emit -> parse roundtrip with datetime [tests/yaml_002.phpt]
  * Segmentation fault (core dumped)
* yaml_emit - serializable [tests/yaml_emit_005.phpt]
  * Warning: yaml_emit(): Emitter error: expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS in /vagrant/pecl-file_formats-yaml/tests/yaml_emit_005.php on line 11
* yaml_parse - general [tests/yaml_parse_001.phpt]
  * Aborted (core dumped)
* Yaml 1.1 Spec - timestamp [tests/yaml_parse_spec_timestamp.phpt]
  * Segmentation fault (core dumped)

There are also a lot of warnings emitted by the compiler when building the extension. Output from my build at https://gist.github.com/anonymous/acdec2d9b6ddb7c23f91

You should adjust the `.travis.yml` in your branch to test against their nightly PHP 7 build:
```
php:
  - nightly
```
When you can get that to pass all of the tests then we can start thinking about the next steps for this.

> Also, I noticed that yaml exists in a couple different places for version control + bug tracking, would it be helpful if I could spend some time merging them into one place?

The canonical version control is here at https://github.com/php/pecl-file_formats-yaml and the bug tracker is [bugs.php.net](https://bugs.php.net/search.php?cmd=display&status=Open&package_name[]=yaml). There are some remnants of the pre-PECL version of the extension at https://code.google.com/p/php-yaml/ that I could probably clean up at bit and remove from the PEAR project profile.

**Comment by Sean-Der** [comment]
Hey @bd808 you rock thank you SO MUCH for catching that, I hadn't set the CFLAGS at all you had in the dev-tools/ directory

I just fixed all the compile warnings, and we travis says we are at 100% :D

**Comment by bd808** [comment]
Green tests! Nice job @Sean-Der.

I didn't want to stop you while you were on a roll, but now I think we should talk a bit about how this will actually end up getting merged. There are basically three ways to approach the PHP7 compat issue:

1. Abandon PHP5 support in the extension
2. Branch and maintain two parallel versions going forward
3. Do some `#ifdef` magic to make PHP5 and PHP7 build out of the same source tree 

This PR is heavily biased towards one of the first two options with all of the fancy new PHP7 macro conversions. Option 1 is right out as far as I'm concerned. PHP5 will be around for quite a while do to LTS distributions (Ubuntu 14.04 will be supported until 2019).

Maintaining parallel branches (option 2) for that long will be a real pain too. I'm already not happy that the version of this extension that got integrated with HHVM is a fork that is drifting from this master in features and bugs. That drift would be theoretically easier to deal with within a single repo but in practice it will still be annoying.

I'd be willing to drop support for versions less than PHP 5.5 if we can come up with a reasonable way to do option 3. I started looking around to find others who are doing the same thing and have found a couple examples so far (https://github.com/jedisct1/libsodium-php/pull/23, https://github.com/andreiz/bloomy/pull/5). I think with a little digging we can probably find other examples to crib from and invent the rest ourselves. It may mean unwinding a few of your simplifications for more verbose constructs that we can make work with both engines, but if we can do it cleanly we may end up with a nice compat header file that others would be interested in using as well.

Getting everything to work on `ZEND_ENGINE_2` and `ZEND_ENGINE_3` at the same time is likely to take a while. I'd be willing to land this on a feature branch so others can test and help more easily. We can work on bringing the feature branch and master together incrementally. Does that sound reasonable to you?

**Comment by Sean-Der** [comment]
@bd808 So... thinking about the changes I made I think it is going to be pretty hard to put things behind some preprocessor logic :/ these are the things I am worried about

* Stack vs Heap allocations - in 5 we return pointers and `*zval != NULL` , in 7 we pass in a stack allocated zvals to modified and then `Z_TYPE_P(*zval) != IS_UNDEF` that is going to be a lot of time wasted.
* HashTable iteration macros - Not the end of the world, but it sure is nice having them :)
* zend_string API - again, just a lot of extra lines 
* A lot of functions have changed from **zval to *zval `zval_ptr_dtor` is the first thing that comes to mind


It is your executive decision, but if you would like I would love to be involved long term and help triage and I would be around to manage two branches (even if all I did was port patches you wrote). I know it will be more work, but it feels good to have a clean code base.

I have decided to do a new branch for ssh2, msgpack and mailparse so far. I may *really* hate myself in 6 months, but so far it has been working.

**Comment by php-pulls** [comment]
**Comment on behalf of bd808 at php.net:**

I have merged this PR as a new [php7 branch](/php/pecl-file_formats-yaml/tree/php7). If I get some time I'd like to see if I can come up with a reasonable compat layer to allow us to build for PHP5 and PHP7 from the same branch, but there is no reason at all to hold this great work hostage hoping for that to happen.

**Comment by bd808** [comment]
Released https://pecl.php.net/package/yaml/2.0.0RC1 built on the php7 branch.

**Pull request closed without merging**
